# Generated by Django 4.2.6 on 2023-11-29 00:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('user', 'query')},
        ),
    ]
