# Generated by Django 4.2.6 on 2023-10-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmPassword',
        ),
    ]
